// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6--x-DBSM-F8zIbcdUqYRk4BkMOSt9G8',
    appId: '1:1007466108564:web:6cb432b9ff6178011c8681',
    messagingSenderId: '1007466108564',
    projectId: 'kigali-directory-81392',
    authDomain: 'kigali-directory-81392.firebaseapp.com',
    storageBucket: 'kigali-directory-81392.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClB0S2K6QhYanuX3Q2TC1JLwfA0nak9VM',
    appId: '1:1007466108564:android:cdd219895d7352261c8681',
    messagingSenderId: '1007466108564',
    projectId: 'kigali-directory-81392',
    storageBucket: 'kigali-directory-81392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEE8HA36sQZwLrebKrGf3wMgWh_UI0j40',
    appId: '1:1007466108564:ios:0efc303e264d63031c8681',
    messagingSenderId: '1007466108564',
    projectId: 'kigali-directory-81392',
    storageBucket: 'kigali-directory-81392.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEE8HA36sQZwLrebKrGf3wMgWh_UI0j40',
    appId: '1:1007466108564:ios:0efc303e264d63031c8681',
    messagingSenderId: '1007466108564',
    projectId: 'kigali-directory-81392',
    storageBucket: 'kigali-directory-81392.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6--x-DBSM-F8zIbcdUqYRk4BkMOSt9G8',
    appId: '1:1007466108564:web:37520bd35fe500741c8681',
    messagingSenderId: '1007466108564',
    projectId: 'kigali-directory-81392',
    authDomain: 'kigali-directory-81392.firebaseapp.com',
    storageBucket: 'kigali-directory-81392.firebasestorage.app',
  );
}
